name: govulncheck
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*
  schedule:
  - cron: 2 2 * * *
jobs:
  govulncheck:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
    - name: go-version
      id: go-version
      run: |
        echo go-version="$(awk '/GO_VERSION:/ { print $2 }' .github/workflows/main.yml | tr -d \')" >> "${GITHUB_OUTPUT}"
    - uses: golang/govulncheck-action@7da72f730e37eeaad891fcff0a532d27ed737cd4
      with:
        go-version-input: ${{ steps.go-version.outputs.go-version }}
